[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_staking_rewards = "BGnGLvL5nBwwPwJtbaqCCRzihjU5uETzv1vo6WTCgS2c"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
